# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
  - board: xiao_ble//zmk
    shield: totem_dongle prospector_adapter
    cmake-args: >
      -DCONFIG_BT_DEVICE_NAME="TOTEM Prospector BT"
      -DCONFIG_USB_DEVICE_PRODUCT="TOTEM Prospector USB"
    artifact-name: totem_prospector
  - board: xiao_ble//zmk
    shield: totem_dongle rgbled_adapter
    artifact-name: totem_rgbdongle

  - board: nice_nano//zmk
    shield: temporal_left nice_view
    extra-conf-file: config/temporal_split.conf
    artifact-name: temporal_left
  - board: nice_nano//zmk
    shield: temporal_right nice_view
    extra-conf-file: config/temporal_split.conf
    artifact-name: temporal_right
  - board: nice_nano//zmk
    shield: temporal_trackpad
    artifact-name: temporal_trackpad
  - board: xiao_ble//zmk
    shield: temporal_dongle prospector_adapter
    cmake-args: >
      -DCONFIG_BT_DEVICE_NAME="Temporal Prospector BT"
      -DCONFIG_USB_DEVICE_PRODUCT="Temporal Prospector USB"
    artifact-name: temporal_prospector
  - board: xiao_ble//zmk
    shield: temporal_dongle rgbled_adapter
    artifact-name: temporal_rgbdongle

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: xiao_settings_reset
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: nice_nano_settings_reset
