# Copyright (c) 2025 Curtis Bollinger
# SPDX-License-Identifier: MIT

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# IMPORTANT: Only enable the display --OR-- the Touchpad
#   You cannot use SPI (display) and I2C (touchpad)
#   on the same instance (e.g. spi0 and i2c0)

# This configuration is for the right half

# -------------------------
# Azoteq Touchpad Configuration
# -------------------------
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_INPUT_TPS43=y
CONFIG_INPUT_THREAD_STACK_SIZE=2048