# Copyright (c) 2025 Curtis Bollinger
# SPDX-License-Identifier: MIT

CONFIG_ZMK_SLEEP=y

# -------------------------
# ZMK Display Configuration
# -------------------------
#CONFIG_ZMK_DISPLAY=n
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
#CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
#CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=100

#CONFIG_LV_Z_MEM_POOL_SIZE=8192

#CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22=y

#CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
#CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y


# -------------------------
# Azoteq Touchpad Configuration
# -------------------------
CONFIG_I2C=y
CONFIG_INPUT_TPS43=y