CONFIG_ZMK_SLEEP=n

CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=75
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=25
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=y
CONFIG_RGBLED_WIDGET_CONN_COLOR_USB=7
