manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: urob
      url-base: https://github.com/urob
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
    - name: dmhuisma
      url-base: https://github.com/dmhuisma
    - name: t4corun
      url-base: https://github.com/t4corun
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: prospector-zmk-module
      remote: carrefinho
      revision: feat/new-status-screens
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk_driver_azoteq
      remote: geeksville
      revision: master
    - name: nice-view-battery-peripheral
      remote: dmhuisma
      revision: zmk_0.4
    - name: zmk_arbitrary_split_data_channel
      remote: t4corun
      revision: bugfix
    - name: zmk-split-status-relay
      remote: dmhuisma
      revision: main
  self:
    path: config
